services:
  - type: web
    name: namuh-smart-trader
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: NHPLUG_APP_KEY
        sync: false
      - key: NHPLUG_APP_SECRET
        sync: false
      - key: NHPLUG_BASE_URL
        value: https://api.nhplug.com:8443
      - key: NHPLUG_AUTH_URL
        value: https://api.nhplug.com:8443
      - key: PROTECTED_CODES
        sync: false
