(function(){
  'use strict';
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const won=n=>(Number(n||0)>=0?'':'-')+Math.abs(Math.round(Number(n||0))).toLocaleString('ko-KR')+'원';
  const pct=n=>(Number(n||0)>=0?'+':'')+Number(n||0).toFixed(2)+'%';
  let searchTimer=null,searchSeq=0,searchAbort=null,searchComposing=false;

  function currentMarket(){if(q('#usModeLabel')?.classList.contains('active'))return 'US';if(q('#krModeLabel')?.classList.contains('active'))return 'KR';const dm=String(document.body.dataset.market||'').toUpperCase();return dm==='US'?'US':'KR'}
  function addWithAlice(){const h=q('.hero-copy h1');if(!h||q('.v34-with-alice'))return;const s=document.createElement('small');s.className='v34-with-alice';s.textContent='with Alice';h.appendChild(s)}
  function cleanHero(){q('#subtitle')?.classList.add('v34-hidden');q('#scheduleCard')?.classList.add('v34-hidden');const pnl=q('#overallPnl')?.parentElement?.querySelector('span');if(pnl)pnl.textContent='실현손익';q('#v33MasterControl')?.remove()}

  function normalizeTop(){
    const top=q('.top-actions'),sw=q('.market-switch'),live=q('.live-chip');if(!top||!sw)return;
    if(!q('#v34AutoBtn')){const b=document.createElement('button');b.id='v34AutoBtn';b.className='v34-auto-btn';b.textContent='AUTO ...';b.addEventListener('click',toggleAuto);top.insertBefore(b,sw)}
    if(live)top.appendChild(live);loadAuto();
  }
  async function loadAuto(){try{const r=await fetch('/api/trading-control',{cache:'no-store'});if(!r.ok)return;const d=await r.json(),b=q('#v34AutoBtn');if(!b)return;b.dataset.enabled=String(Boolean(d.new_entries_enabled));b.textContent=d.new_entries_enabled?'AUTO ON':'AUTO OFF';b.classList.toggle('off',!d.new_entries_enabled)}catch(_){}}
  async function toggleAuto(){const b=q('#v34AutoBtn');if(!b)return;const next=b.dataset.enabled!=='true';b.disabled=true;try{const r=await fetch('/api/trading-control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({new_entries_enabled:next})});if(!r.ok)throw new Error(r.status);await loadAuto()}catch(e){console.error(e)}finally{b.disabled=false}}

  function buildControlStrip(){
    const strip=q('.control-strip');if(!strip)return;q('#v33MasterControl')?.remove();qa('.control-strip > .control-stat').forEach(x=>x.remove());strip.classList.add('v34-control-strip');
    if(!q('#v34SearchBox')){const box=document.createElement('div');box.id='v34SearchBox';box.className='v34-search-box';box.innerHTML='<small>STOCK SEARCH</small><div class="v34-search-line"><input id="v34SearchInput" autocomplete="off" autocapitalize="off" spellcheck="false" enterkeyhint="search" placeholder="종목명 / 종목코드 검색"><span>⌕</span></div><div id="v34SearchResults" class="v34-search-results"></div>';strip.appendChild(box);const input=q('#v34SearchInput');input?.addEventListener('compositionstart',()=>{searchComposing=true;clearTimeout(searchTimer)});input?.addEventListener('compositionend',e=>{searchComposing=false;clearTimeout(searchTimer);searchTimer=setTimeout(()=>searchStocks(e.target.value),50)});input?.addEventListener('input',e=>{if(searchComposing||e.isComposing)return;clearTimeout(searchTimer);searchTimer=setTimeout(()=>searchStocks(e.target.value),160)});input?.addEventListener('focus',e=>{document.body.classList.add('v34-search-active');positionSearchResults();if(e.target.value.trim())searchStocks(e.target.value)});input?.addEventListener('blur',()=>setTimeout(()=>{if(!document.activeElement?.closest?.('#v34SearchBox'))document.body.classList.remove('v34-search-active')},180));document.addEventListener('click',e=>{if(!e.target.closest('#v34SearchBox'))closeSearch()});window.visualViewport?.addEventListener('resize',positionSearchResults);window.visualViewport?.addEventListener('scroll',positionSearchResults);window.addEventListener('resize',positionSearchResults)}
    if(!q('#v34DisclosureAlerts')){const box=document.createElement('div');box.id='v34DisclosureAlerts';box.className='v34-disclosure-slot';strip.appendChild(box)}
    if(!q('#v34FlowAlerts')){const box=document.createElement('div');box.id='v34FlowAlerts';box.className='v34-alert-slot';box.innerHTML='<div class="v34-alert-idle"><small>KR ABNORMAL FLOW</small><b>직전 5거래일 동시간대 이상수급 감시</b></div>';strip.appendChild(box)}
  }
  function closeSearch(){const r=q('#v34SearchResults');r?.classList.remove('open');document.body.classList.remove('v34-search-active')}
  function positionSearchResults(){const result=q('#v34SearchResults'),input=q('#v34SearchInput');if(!result||!input)return;if(innerWidth>780){result.style.position='';result.style.left='';result.style.right='';result.style.top='';result.style.maxHeight='';result.style.zIndex='';return}const vv=window.visualViewport,viewTop=vv?.offsetTop||0,viewH=vv?.height||innerHeight,rect=input.getBoundingClientRect();let top=Math.max(viewTop+8,rect.bottom+8);const viewBottom=viewTop+viewH;if(viewBottom-top<150)top=Math.max(viewTop+56,viewBottom-260);result.style.position='fixed';result.style.left='10px';result.style.right='10px';result.style.top=`${Math.round(top)}px`;result.style.maxHeight=`${Math.max(130,Math.floor(viewBottom-top-10))}px`;result.style.zIndex='10050'}
  async function searchStocks(raw){
    const text=String(raw||'').trim(),result=q('#v34SearchResults'),input=q('#v34SearchInput');if(!result)return;
    if(!text){if(searchAbort)searchAbort.abort();result.innerHTML='';closeSearch();return}
    const seq=++searchSeq,market=currentMarket();if(searchAbort)searchAbort.abort();searchAbort=new AbortController();
    result.innerHTML='<div class="v34-search-empty">종목 마스터 검색 중…</div>';result.classList.add('open');document.body.classList.add('v34-search-active');positionSearchResults();
    try{
      const r=await fetch(`/api/v34/search?market=${market}&q=${encodeURIComponent(text)}`,{cache:'no-store',signal:searchAbort.signal});
      if(!r.ok)throw new Error(`HTTP ${r.status}`);
      const d=await r.json();if(seq!==searchSeq||String(input?.value||'').trim()!==text||currentMarket()!==market)return;const rows=d.items||[];
      if(!rows.length){result.innerHTML=d.master_error?'<div class="v34-search-empty">종목 마스터 재연결 중 · 잠시 후 다시 검색</div>':'<div class="v34-search-empty">검색 결과 없음</div>';positionSearchResults();return}
      result.innerHTML=rows.map((x,i)=>{const px=Number(x.price||0),priceText=px>0?(x.market==='US'?'$'+px.toLocaleString(undefined,{maximumFractionDigits:4}):px.toLocaleString('ko-KR')+'원'):(x.tracked?'현재가 수신 대기':'선택 시 현재가 연결');return `<button type="button" data-rank="${i}" data-v34-stock="${esc(x.market)}/${esc(x.code)}"><span><b>${esc(x.name||x.code)}</b><small>${esc(x.code)} · ${esc(x.sector||'업종 미분류')}</small></span><em>${esc(priceText)}</em></button>`}).join('');
      const openStock=async b=>{const [m,code]=(b.dataset.v34Stock||'').split('/');if(!m||!code)return;const selected=`${m}/${code}`;result.querySelectorAll('button').forEach(x=>x.disabled=true);input?.blur();try{const tr=await fetch(`/api/v34/track/${encodeURIComponent(m)}/${encodeURIComponent(code)}`,{method:'POST',cache:'no-store'});if(!tr.ok)throw new Error(`track ${tr.status}`);const td=await tr.json();if(td.ok===false)throw new Error(td.error||'track failed');if((b.dataset.v34Stock||'')!==selected)return;location.href=`/stock/${encodeURIComponent(m)}/${encodeURIComponent(code)}`}catch(e){console.error(e);result.querySelectorAll('button').forEach(x=>x.disabled=false);result.insertAdjacentHTML('afterbegin','<div class="v34-search-empty">종목 연결 실패 · 다시 눌러주세요</div>')}};
      result.querySelectorAll('[data-v34-stock]').forEach(b=>b.addEventListener('click',()=>openStock(b),{once:true}));
      if(input&&!input.dataset.v347Enter){input.dataset.v347Enter='1';input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();result.querySelector('[data-v34-stock]')?.click()}})}positionSearchResults();
    }catch(e){if(e?.name==='AbortError')return;console.error(e);if(seq===searchSeq){result.innerHTML='<div class="v34-search-empty">검색 서버 연결 오류 · 다시 시도</div>';positionSearchResults()}}
  }

  async function loadFlowAlerts(){
    const slot=q('#v34FlowAlerts');if(!slot)return;if(currentMarket()!=='KR'){slot.innerHTML='<div class="v34-alert-idle"><small>US MARKET</small><b>종목 검색 · SEC 공시 분석</b></div>';return}
    try{const r=await fetch('/api/v34/flow-alerts',{cache:'no-store'}),d=await r.json(),rows=d.items||[];if(!rows.length){slot.innerHTML='<div class="v34-alert-idle"><small>KR ABNORMAL FLOW</small><b>직전 5거래일 동시간대 이상수급 감시</b></div>';return}slot.innerHTML='<div class="v34-alerts-wrap">'+rows.slice(0,3).map((x,i)=>{const f=x.flow||{},side=k=>f[k]?.side||'대기';return `<button class="v34-flow-alert" data-stock="KR/${esc(x.code)}"><div class="v34-flow-head"><span>${i+1}순위</span><b>${esc(x.name||x.code)}</b><em>${Number(x.priority_score||0).toFixed(0)}점</em></div><div class="v34-flow-core">거래량 ${Number(x.volume_ratio_5d_1m||0).toFixed(1)}× · 체결 ${Number(x.execution_strength||0).toFixed(0)} (${Number(x.execution_accel_60s||0)>=0?'+':''}${Number(x.execution_accel_60s||0).toFixed(1)}) · 5분 상승</div><div class="v34-flow-sides"><span>외 ${side('foreign')}</span><span>기관 ${side('institution')}</span><span>연기금 ${side('pension')}</span><span>프로그램 ${side('program')}</span></div></button>`}).join('')+'</div>'}catch(e){console.error(e)}
  }
  function disclosureImpact(e){if(e.blocked)return '신규진입 차단';return Number(e.score||0)>0?'+5점':'-5점'}
  async function loadDisclosureAlerts(){
    const slot=q('#v34DisclosureAlerts');if(!slot)return;const market=currentMarket();
    try{const r=await fetch(`/api/v34/disclosure-alerts?market=${market}`,{cache:'no-store'});if(!r.ok)throw new Error(r.status);const d=await r.json(),rows=d.items||[],total=Number(d.unread_total||rows.length||0);if(!rows.length){slot.classList.remove('active');slot.innerHTML='';return}slot.classList.add('active');const shown=rows.slice(0,3);slot.innerHTML=`<div class="v342-disclosure-title"><div><small>IMPORTANT DISCLOSURE · UNREAD</small><b>미확인 중요공시 ${total}건</b></div><span>읽기 전까지 유지 · ${d.market_open?'장중 집중분석':'다음 거래일 분석 대기'}</span></div><div class="v342-disclosure-wrap">${shown.map(e=>`<button type="button" class="v342-disclosure-alert ${e.blocked?'blocked':e.sentiment==='positive'?'positive':'negative'}" data-v342-disclosure="${esc(e.id)}" data-v342-market="${esc(e.market)}" data-v342-code="${esc(e.code)}"><div class="v342-disclosure-top"><span>미확인</span><b>${esc(e.name||e.code)}</b><em>${esc(disclosureImpact(e))}</em></div><div class="v342-disclosure-titleline">${esc(e.title)}</div><div class="v342-disclosure-meta"><span>${esc(e.date||'')} ${esc(e.time||'')}</span><span>${esc(e.source||'')}</span><strong>${esc(e.focus_label||'다음 거래일 집중분석')}</strong></div></button>`).join('')}</div>${total>3?`<div class="v342-disclosure-more">외 ${total-3}건 미확인</div>`:''}`;slot.querySelectorAll('[data-v342-disclosure]').forEach(b=>b.addEventListener('click',async()=>{const id=b.dataset.v342Disclosure||'',m=b.dataset.v342Market||market,code=b.dataset.v342Code||'';b.disabled=true;try{await fetch(`/api/v34/disclosure-alerts/${encodeURIComponent(id)}/read`,{method:'POST',cache:'no-store'})}catch(e){console.error(e)}if(code)location.href=`/stock/${encodeURIComponent(m)}/${encodeURIComponent(code)}`;else loadDisclosureAlerts()}))}catch(e){console.error(e)}
  }
  function updateSearchPlaceholder(){const i=q('#v34SearchInput');if(i)i.placeholder=currentMarket()==='US'?'미국 종목명 / 티커 검색':'국내 종목명 / 종목코드 검색'}
  async function enhanceCalendarDay(date){if(!date)return;const [y,m]=date.split('-').map(Number);try{const r=await fetch(`/api/pnl-calendar?scope=stock&year=${y}&month=${m}`,{cache:'no-store'}),d=await r.json(),row=d.days?.[date],box=q('#profitDetailList');if(!box)return;box.innerHTML=row?(row.trades||[]).map(t=>`<div class="profit-row v34-profit-row"><div><b>${esc(t.name||t.code)}</b> <span class="market-badge">${esc(t.market||'')}</span><br><small>${esc(t.date||date)} ${esc(t.time||'')} KST · ${Number(t.qty||0).toLocaleString()}주 · 매도 ${t.market==='US'?'$'+Number(t.price||0).toLocaleString(undefined,{maximumFractionDigits:4}):Number(t.price||0).toLocaleString('ko-KR')+'원'}</small></div><div><b class="${Number(t.pnl||0)>=0?'pos':'neg'}">${won(t.pnl)}</b><br><small>${pct(t.pnl_pct)}</small></div></div>`).join(''):'<div class="empty">실현 매매 없음</div>'}catch(e){console.error(e)}}
  function watchMode(){const obs=new MutationObserver(()=>{updateSearchPlaceholder();setTimeout(loadDisclosureAlerts,80);setTimeout(loadFlowAlerts,100)});['#krModeLabel','#usModeLabel'].forEach(s=>{const el=q(s);if(el)obs.observe(el,{attributes:true,attributeFilter:['class']})})}
  function init(){addWithAlice();cleanHero();normalizeTop();buildControlStrip();updateSearchPlaceholder();watchMode();document.addEventListener('click',e=>{const d=e.target.closest?.('[data-date]');if(d)setTimeout(()=>enhanceCalendarDay(d.dataset.date),30)});loadDisclosureAlerts();loadFlowAlerts();setInterval(loadAuto,12000);setInterval(loadDisclosureAlerts,7000);setInterval(loadFlowAlerts,4000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
